### ISSUE TITLE
[PE-D][Tester C] Invalid Phone Number in Example Command in FINDvisor Command Summary

### ISSUE THREAD

**Issue by nus-se-script** [AY2324S2-CS2103-F15-1/tp#231] opened 2024-04-05 19:56 UTC
![image.png](https://raw.githubusercontent.com/rizkidelta/ped/main/files/ab8f0711-2b63-4472-9151-2791877b6983.png)

![image.png](https://raw.githubusercontent.com/rizkidelta/ped/main/files/23f83c78-139e-401c-877a-a3006be52522.png)

In the command summary section of the FINDvisor user guide, the example provided for adding a new contact includes an invalid phone number format, resulting in an error when attempting to follow the example as given.

Details:

Section: Command Summary.
Faulty Example Command: add n/James Ho p/22224444 e/jamesho@example.com a/123, Clementi Rd, 1234665 t/friend t/colleague.
Issue: The phone number 22224444 does not adhere to the specified format of Singapore telephone numbers, which the guide states should be in the format 9XXXXXXX or 8XXXXXXX.

-------------
Labels: `severity.Medium` `type.DocumentationBug`
original: rizkidelta/ped#4

**Comment by Javiery3889** [comment] 2024-04-10 01:15
Just realised this might be a duplicate of #251, would it be better to mark this as a duplicate?

@Dethada @KohGuanZeh @Arixeyeion @YuZizhen

**Closed** 2024-04-13 15:02 UTC
Labels: type.documentation
