### ISSUE TITLE
[PE-D][Tester E] Edit command leads to invalid command format instead of invalid index error 

### ISSUE THREAD

**Issue by nus-se-script** [AY2324S2-CS2103-F15-1/tp#208] opened 2024-04-05 16:52 UTC
## Describe the bug
When executing `edit 0 n/yash`, the result box shows an invalid command format error even if the format is correct and just the index parameter is wrong. This is inconsistent with executing `edit 3 n/yash` for example when there is only 1 person in the list, which rightly identifies and renders invalid index error.

## To Reproduce
Execute `edit 0 n/[valid name]` on a running application 

## Expected behavior
"Person index provided is invalid" error in the result display

## Screenshots/Video

Actual behavior, 

![image.png](https://raw.githubusercontent.com/yashpola/ped/main/files/eb841f2c-00ad-4ae3-858e-fd11b40fa70f.png)

Expected behavior, 

![image.png](https://raw.githubusercontent.com/yashpola/ped/main/files/f036812d-4fb8-43ac-b26a-e6611434b431.png)

-------------
Labels: `severity.Low` `type.FunctionalityBug`
original: yashpola/ped#1

**Comment by KohGuanZeh** [comment] 2024-04-07 10:03
Duplicate of #214

**Closed** 2024-04-07 11:01 UTC
Labels: duplicate
